### ISSUE TITLE
NestJS and kirka Error

### ISSUE THREAD

**Issue by overpod** [numfin/kirka#3]
I want to use your wonderful solution with NSTHS.
In development mode I get an error.
```
[8:45:24 AM] Starting compilation in watch mode...

[8:45:26 AM] Found 0 errors. Watching for file changes.


/Users/overpod/Documents/projects/apex/portal-back/dist/comments/comments.service.js:14
const kirka_1 = require("kirka");
                ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/overpod/Documents/projects/apex/portal-back/node_modules/kirka/dist/index.js from /Users/overpod/Documents/projects/apex/portal-back/dist/comments/comments.service.js not supported.
Instead change the require of index.js in /Users/overpod/Documents/projects/apex/portal-back/dist/comments/comments.service.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/overpod/Documents/projects/apex/portal-back/dist/comments/comments.service.js:14:17)
    at Object.<anonymous> (/Users/overpod/Documents/projects/apex/portal-back/dist/comments/comments.module.js:12:28)
    at Object.<anonymous> (/Users/overpod/Documents/projects/apex/portal-back/dist/app/app.module.js:18:27)
    at Object.<anonymous> (/Users/overpod/Documents/projects/apex/portal-back/dist/main.js:6:22)
```
The project builds fine

Help me please. I really want to fix this.

**Comment by numfin** [comment]
fixed
